name: 'mill test'
on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
jobs:
  test:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ '8', '11' ]
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Setup java'
        uses: 'actions/setup-java@v1'
        with:
          java-version: ${{ matrix.java }}
      - name: 'Run tests'
        run: '- ./mill -i __.test'
